// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kunhebaifgfclgypaaws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bmhlYmFpZmdmY2xneXBhYXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDIzMTcsImV4cCI6MjA2NDYxODMxN30.uFctAVzPG8y7ttI2y6kBo31ff6yjeKzopakOAwywZcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);